models.py
import datetime, re
from app import db

def slugify(s):
    return re.sub('[^\w]+', '-', s).lower()

entry_tags = db.Table('entry_tags',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
    db.Column('entry_id', db.Integer, db.ForeignKey('entry.id'))
    )

class Entry(db.Model):
    STATUS_PUBLIC = 0
    STATUS_DRAFT = 1
    STATUS_DELETED = 2

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)
    body = db.Column(db.Text)
    status = db.Column(db.SmallInteger, default=STATUS_PUBLIC)
    created_timestamp = db.Column(db.DateTime, default=datetime.datetime.now)
    modified_timestamp = db.Column(
        db.DateTime,
        default=datetime.datetime.now,
        onupdate=datetime.datetime.now)

    tags = db.relationship('Tag', secondary=entry_tags,
        backref=db.backref('entries', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Entry, self).__init__(*args, **kwargs) # Call parent constructor.
        self.generate_slug()

    def generate_slug(self):
        self.slug = ''
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Entry: %s>' % self.title
        

class Tag(db.Model):
        """docstring for Tag"""
        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.String(64), unique=True)
        slug = db.Column(db.String(64))

        def __init__(self, *args, **kwargs):
            super(Tag, self).__init__(*args, **kwargs)
            self.slug = slugify(self.name)

        def __repr__(self):
            return '<Tag %s>' % self.name
                

entries/forms.py
import wtforms
from wtforms.validators import DataRequired
from models import Tag

from models import Entry 

class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            #Display tags as a comma seperated list
            return ', '.join([tag.name for tag in self.data])
        return ''

    def get_tags_from_string(self, tag_string):
        raw_tags = tag_string.split(',')

        #filter out empty tag names
        tag_names = [name.strip() for name in raw_tags if name.strip()]

        #Query the database and retrieve any tags we have alraedy saved
        existing_tags = Tag.query.filter(Tag.name.in_(tag_names))

        #Determine which tag names are new
        new_names = set(tag_names) - set([tag.name for tag in existing_tags])

        # Create a list of unsaved Tag instances for the new tags
        new_tags = [Tag(name=name) for name in new_names]

        #Return al the existing tags + all the new, unaved tags
        return list(existing_tags) + new_tags

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = self.get_tags_from_string(valuelist[0])
        else:
            self.data = []


class EntryForm(wtforms.Form):    
    title = wtforms.StringField(        
        'Title',        
        validators=[DataRequired()])   
    body = wtforms.TextAreaField(        
        'Body',        
        validators=[DataRequired()])    
    status = wtforms.SelectField(        
        'Entry status',        
        choices=(            
            (Entry.STATUS_PUBLIC, 'Public'),            
            (Entry.STATUS_DRAFT, 'Draft')),        
        coerce=int) 
    tags = TagField(
        'Tags',
        description='Separate multiple tags with commas.')   

    def save_entry(self, entry):        
        self.populate_obj(entry)        
        entry.generate_slug()        
        return entry

class ImageForm(wtforms.Form):
    file = wtforms.FileField('Image file')
        

app.py
from flask import Flask
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy

from config import Configuration #import our configuation data

app = Flask(__name__)


app.config.from_object(Configuration)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

entries/blueprint.py
from flask import Blueprint, flash, redirect, render_template, g, request, url_for
from werkzeug import secure_filename

from helpers import object_list
from models import Entry, Tag
from app import app, db
from entries.forms import EntryForm, ImageForm
import os

entries = Blueprint('entries', __name__, template_folder='templates')

def entry_list(template, query, **context):
    valid_statuses = (Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT)
    query = query.filter(Entry.status.in_(valid_statuses))
    if request.args.get('q'):
        search = request.args.get['q']
        query = query.filter(
            (Entry.body.contains(search)) |
            (Entry.title.contains(search)))

    return object_list(template, query, **context)

def get_entry_or_404(slug, author=None):
    query = Entry.query.filter(Entry.slug == slug)
   # if author:
       # query = query.filter(Entry.author == author)
    #else:
       # query = filter_status_by_user(query)
    return query.first_or_404()

@entries.route('/')
def index():
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)

@entries.route('/image-upload/', methods=['GET', 'POST'])
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'], 
                secure_filename(image_file.filename))
            image_file.save(filename)
            flash('Saved %s' % os.path.basename(filename), 'success')
            return redirect(url_for('entries.index'))
    else:
        form = ImageForm()

    return render_template('entries/image_upload.html', form=form)


@entries.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    return object_list('entries/tag_index.html', tags)

@entries.route('/tags/<slug>/')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)

@entries.route('/create/', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            entry = form.save_entry(Entry())
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm()
    
    return render_template('entries/create.html', form=form)

@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
def edit(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" has ben saved' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)

    return render_template('entries/edit.html', entry=entry, form=form)

@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
def delete(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" has been deleted' % entry.title, 'success')
        return redirect(url_for('entries.index'))

    return render_template('entries/delete.html', entry=entry)

@entries.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug)
    return render_template('entries/detail.html', entry=entry)

main.py
from app import app, db #import our Flask app
import models
import views

#registering blueprint
from entries.blueprint import entries 
app.register_blueprint(entries, url_prefix='/entries')

if __name__ == '__main__':
    app.run()

views.py
from flask import render_template, request
from app import app

@app.route('/')
def homepage():
    name = request.args.get('name')
    number = request.args.get('number')
    return render_template('homepage.html', name=name, number=number)

entries/templates/entries/base_entries.html
{% extends "base.html" %}

{% block sidebar %}
    <form class="form-inline well" method="get" role="form">
        <div class="input-group">
            <input class="form-control input-xs" name="q" placeholder="Search..." value="{{ request.args.get('q', '') }}">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go</button>
            </span>
        </div>
    </form>
{% endblock %}

{% block content %}
    {% include "includes/list.html" %}
    {% include "includes/page_links.html" %}
{% endblock %}

entries/templates/entries/create.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Create new entry{% endblock %}

{% block content_title %}Create new entry{% endblock %}

{% block content %}
<form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
    {% for field in form %}
        {{ form_field(field) }}
    {% endfor %}
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-default">Create</button>
        <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
    </div>          
</div>
</form>
{% endblock %}

entries/templates/entries/delete.html
{% extends "base.html" %}

{% block title %}{{ entry.title }}{% endblock %}

{% block content_title %}{{ entry.title }}{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.delete', slug=entry.slug) }}" method="post">
        <fieldset>
            <legend>Delete this entry?</legend>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}"></a>
        </fieldset>
    </form>    
{% endblock %}

entries/templates/entries/detail.html
{% extends "base.html" %}

{% block title %}{{ entry.title}}{% endblock %}

{% block sidebar %}
    <ul class="well nav nav-list">
        <li><h4>Tags</h4></li>
        {% for tag in entry.tags %}
        <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a></li>
        {% endfor %}
        {% if g.user == entry.author %}
        <li><h4>Actions</h4></li>
        <li><a href="{{ url_for('entries.edit', slug=entry.slug)}}">Edit</a></li>
        <li><a href="{{ url_for('entries.delete', slug=entry.slug)}}">Delete</a></li>
        {% endif %}
    </ul>
    <p>Published {{ entry.created_timestamp.strftime('%m/%d/%Y')}}</p>
{% endblock %}

{% block content %}
    {{ entry.body }}
{% endblock%}

entries/templates/entries/edit.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Edit {{ entry.title }}{% endblock %}

{% block content_title %}Edit {{ entry.title }}{% endblock %}

{% block content %}
<form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
    {% for field in form %}
        {{ form_field(field) }}
    {% endfor %}
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-default">Save</button>
        <a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
    </div>          
</div>
</form>
{% endblock %}

entries/templates/entries/image_upload.html
{% extends "base.html" %}
{% from "macros/form_field.html"  import form_field %}

{% block title %}Upload an image{% endblock %}

{% block content_title %}Upload an image{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.image_upload') }}" enctype="multipart/form-data" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Upload</button>
                <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

entries/templates/entries/index.html
{% extends "entries/base_entries.html" %}

{% block title %}Entries{% endblock %}

{% block content_title %}Entries{% endblock %}

entries/templates/entries/tag_detail.html
{% extends "entries/base_entries.html" %}
{% block title %}Tags{% endblock %}
{% block content_title %}Tags{% endblock %}

entries/templates/entries/tag_index.html
{% extends "base.html" %}

{% block title %}Tags{% endblock %}

{% block content_title %}Tags{% endblock %}

{% block content %}
    {% for tag in object_list.items %}
        <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
    {% endfor %}
    {% include "includes/page_links.html" %}
{% endblock %}

entries/templates/includes/list.html
{% for entry in object_list.items %}
<p><a href="{{ url_for('entries.detail', slug=entry.slug) }}">{{ entry.title }}</a></p>
{% endfor %}

entries/templates/macros/form_field.html
{% macro form_field(field) %}
    <div class="form-group{% if field.errors %} has-error has-feedback{% endif %}">
        {{ field.label(class="col-sm-3 control-label") }}
        <div class="col-sm-9">
            {{ field(class='form-control', **kwargs) }}
            {% if field.errors %}<span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>{% endif %}  
            {% if field.description %}<span class="help-block">{{ field.description | safe }}</span>{% endif %}    
            {% for error in field.errors %}<span class="help-block">{{ error }}</span>{% endfor %}    
        </div>  
    </div>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} | My Blog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css">
   
    <style type="text/css">
        body { padding-top: 60px; }
    </style>
    {% block extra_styles %} {% endblock %}

    <script src="https://code.jquery.com/jquery-1.10.2.min.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css"></script>
    {% block extra_scripts %} {% endblock %}
</head>
<body class="{% block body_class %} {% endblock %}">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collpse" data-target=".navbar-collapse">
                    <span class="sr-only">toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">{% block branging %}My Blogg{% endblock %}</a>
            </div>
            <div class="collpse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('homepage') }}">Home</a></li>
                    <li><a href="{{ url_for('entries.index') }}">Blog</a></li>
                    <li><a href="{{ url_for('entries.tag_index') }}">Tags</a></li>
                    {% block extra_nav %}{% endblock %}
                </ul>
            </div>
        </div>       
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h1>{% block content_title %}{% endblock %}</h1>
                {% for category, message in get_flashed_messages(with_categories=true) %}
                    <div class="alert alert-dismissable alert-{{ category }}" >
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                {% endfor %}
                {% block content %}          
                {% endblock %}
            </div>
            <div class="col-md-3">          
            {% block sidebar %}          
            <ul class="well nav nav-stacked">            
                <li><a href="#">Sidebar item</a></li>          
            </ul>          
            {% endblock %}
        </div>
    </div>
    <div class="row">
        <hr />
        <footer>
          <p>&copy; S-Monk</p>
        </footer>
      </div>
    </div>
</body>
</html>

templates/homepage.html
{% extends "base.html" %}

{% block content_title %}Welcome to blogg - the place to air my thoughts{% endblock %}

{% block content %}

    

    <p>your name is {{  name|default('<unknown>', True ) }} and you did not provide a number.</p>
{% endblock %}

templates/includes/page_links.html
<ul class="pagination">
    <li {% if not object_list.has_prev %} class="disabled" {% endif %}>
        {% if not object_list.has_prev %}
            <a href="./?page={{ object_list.prev_num }}">&laquo;</a>
        {% else %}
            <a href="#">&laquo;</a>
        {% endif %}  
    </li>
    {% for page in object_list.iter_pages() %}
        <li>
            {% if page %}
                <a {% if page == object_list.page %} class="active" {% endif %} href="./?page={{ page }}">{{ page }}</a>
            {% else %}
                <a class="disabled">...</a>
            {% endif %}
        </li>
    {% endfor %}
    <li{% if not object_list.has_next %} class="disabled"{% endif %}>
        {% if object_list.has_next %}
            <a href="./?page={{ object_list.next_num }}">&raquo;</a>
        {% else %}
            <a href="#">&raquo;</a>    
        {% endif %}  
    </li>
</ul>